name: Apple Music Schedule Scraper

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch: # Allow manual trigger
  push:
    branches: [ main ]
    paths:
      - 'scrape_apple_music_schedule.py'
      - 'requirements.txt'
      - '.github/workflows/scrape-schedule.yml'

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install chromium
        
    - name: Run scraper
      run: |
        python scrape_apple_music_schedule.py
        
    - name: Upload schedule data
      uses: actions/upload-artifact@v4
      with:
        name: apple-music-schedule-${{ github.run_number }}
        path: apple_music_schedule.json
        
    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add apple_music_schedule.json
        git diff --staged --quiet || git commit -m "Update Apple Music schedule data"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}